version: '3'

services:
    db-headless:
        container_name: db-headless
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
            - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - MYSQL_USER=${WORDPRESS_DB_USER}
        image: mariadb

    wp-headless:
        build: .
        command: bash -c 'install_wordpress && apache2-foreground'
        container_name: wp-headless
        depends_on:
            - db-headless
        env_file: ./.env
        user: www-data
        volumes:
            - ./wordpress:/var/www/html
            - ./docker/install_wordpress.sh:/usr/local/bin/install_wordpress
            - ./docker/migratedb_import.sh:/usr/local/bin/migratedb_import
            - ./docker/postlightheadlesswpstarter.wordpress.xml:/var/www/postlightheadlesswpstarter.wordpress.xml
            - ./docker/images:/var/www/images
            - ./docker/plugins:/var/www/plugins
    frontend:
        command: bash -c 'yarn && yarn start'
        container_name: frontend

        image: node:17

        user: node
        volumes:
            - ./frontend:/home/node/app
        working_dir: /home/node/app
    frontend-graphql:
        command: bash -c 'yarn && yarn start'
        container_name: frontend-graphql

        image: node:17

        user: node
        volumes:
            - ./frontend-graphql:/home/node/app
        working_dir: /home/node/app
